### ISSUE TITLE
Remove active_model_serializers

### ISSUE THREAD

**Issue by wildchild** [emberjs/ember-rails#134]
Is it really depends on active_model_serializers? Just deleted from gemspec and tests passes. Shouldn't we remove it?

**Comment by nbibler** [comment]
It seems reasonable to remove `active_model_serializers` as a hard dependency of `ember-rails`, especially since `ember-rails` makes no use whatsoever of AMS.  Further, `ember-rails` has to have callouts in the README for how to work around changes to `render(:json)` introduced in Rails by AMS.

Odd to force people to use AMS when they could easily render their own JSON in many cases. And, over the past few years, other alternatives have appeared (rabl, for example).

At the end of the day, `ember-rails` doesn't actually use AMS, so it seems wrong to list is as a hard dependency in the gemspec.
