### ISSUE TITLE
 Assertion failed: Ember Views require jQuery 1.7, 1.8, 1.9, 1.10, or 2.0 ember.js?

### ISSUE THREAD

**Issue by orbitalmedia** [emberjs/ember-rails#336]
Hi, new to this project - not sure if this is the place to ask questions?

I'm using rails 4.0.2 and ruby 2.0.0p247 ,  basically at the App.application.create() stage and trying to get past this first error. I have jquery at the top of my require list, the debug console outputs Jquery 1.11.0 as the version. The chrome add-on for ember doesn't recognise the app as an Ember app however. Any clues what this might be?

Thanks!
Mike

 Assertion failed: Ember Views require jQuery 1.7, 1.8, 1.9, 1.10, or 2.0 ember.js?body=1:3286
logToConsole ember.js?body=1:3286
Ember.assert ember.js?body=1:74
(anonymous function) ember.js?body=1:20594
(anonymous function) ember.js?body=1:20604
(anonymous function) ember.js?body=1:40569
DEBUG: ------------------------------- ember.js?body=1:3286
DEBUG: Ember      : 1.3.0 ember.js?body=1:3286
DEBUG: Handlebars : 1.2.1 ember.js?body=1:3286
DEBUG: jQuery     : 1.11.0 ember.js?body=1:3286
DEBUG: -------------------------------

**Comment by Bharatupgraded** [comment]
I am also facing same issue, Any suggestion

**Comment by tricknotes** [comment]
@Bharatupgraded What ember version do you use?
I think current latest ember 1.12.0 will work well.

**Comment by gemmadlou** [comment]
I was using Bower version 1.4.1 when I came across a similar error. However, now I'm using Bower 1.7.1.

**The error was:**
Uncaught Error: Assertion Failed: Ember Views require jQuery between 1.7 and 2.1

**The resolution I found is on Stack Overflow but I thought I'd share it here:**
"This is a bug due to a new version of jQuery which ember is not yet able to handle. For now you can change the following line in your bower.json file. Then run bower install and it should work."

   "jquery": "^1.11.3",
   to
   "jquery": "1.11.3",

http://stackoverflow.com/questions/34702284/getting-uncaught-error-assertion-failed-ember-views-require-jquery-between-1
