### ISSUE TITLE
scaffolted es6 component does not work

### ISSUE THREAD

**Issue by NikolaMandic** [emberjs/ember-rails#505]
it gives compile error that it cannot find functions like require and define

**Comment by tricknotes** [comment]
Could you provide repo code?
Such as your repository, executed command and result, generated files or something.

**Comment by NikolaMandic** [comment]
after I used template

     rails new my-app -m http://emberjs.com/edge_template.rb

I ran
    rails g ember:component exi --javascript-engine=es6

and then I got on fresh project
    Uncaught ReferenceError: define is not defined

coffee script version works

**Comment by dipil-saud** [comment]
Got the same error when bootstrapping a new project with 
```
rails g ember:bootstrap --javascript-engine=es6
```
Currently worked around the issue by adding ```//= require ember/loader``` before requiring the environment file in application.es6

**Comment by tricknotes** [comment]
`//= require ember-rails/application` is required.

It will be included in `app/assets/javascripts/application.es6` that generated by `rails g ember:bootstrap --javascript-engine=es6`.
(See for detail: https://github.com/emberjs/ember-rails/tree/v0.20.1#for-es6-support )

However, as @dipil-saud says, it causes the same error.
This cause is that there is redundant file (`app/assets/javascripts/application.coffee`) that generated by ` rails new my-app -m http://emberjs.com/edge_template.rb` is exist.

Please remove `application.coffee`.
I think it works fine.

I'm closing this issue but it isn't fixed yet, feel free to reopen this :-)
