### ISSUE TITLE
Sprockets cannot find ember/loader

### ISSUE THREAD

**Issue by nachootal** [emberjs/ember-rails#546]
When precompiling the assets with sprockets v3.7.1 in a rails v4.2.8 with ember-rails v0.21.0  I get into this situation in which sprockets cannot find "ember/loader". See [log](https://hastebin.com/epajuyabud.hs).

While debugging sprockets to get to the cause I've found what I think is the case:

- As the type of application.module.es6 is ecmascript module, this is set by sprockets as the acceptance for the required files. In this case loader.js, resolver.js and load-initializers.js from ember-cli-assets gem and shims.js from ember-rails gem. Of course, these files, as might be seen by its extension, are not ecmascript6 module detected but regular javascript files.

I changed the extension on all these files to file_name.module.es6 and tried precompiling again and it seems it finishes without precompiling but don't find this is a good fix.

Is this a well known issue and is there a proper fix of configuration for this?.

**Comment by tricknotes** [comment]
It seems this issue caused by the logical conflict with sprockets-rails 2 and ember-es6-template 0.6.
The one of solutions is using sprockets-rails 3.
However it is locked by [ember-emblem-template](https://github.com/botandrose/ember-emblem-template/blob/v0.4.0/ember-emblem-template.gemspec#L22) 😢 

@nachootal 
Could you try my PR against ember-emblem-template ?
https://github.com/botandrose/ember-emblem-template/pull/4

**Comment by nachootal** [comment]
Hi @tricknotes, I tested and I saw the sprockets-rails updated to 3.2.0. Thanks for your changes. However this caused another error on my installation that I'm not sure whether is linked to the previous. You can see [here](https://hastebin.com/abesarihes.vbs) the output of bundle exec rake assets:precompile RAILS_ENV=production --trace

**Comment by nachootal** [comment]
I see this is related to emblem-rails and emblem-rails is not maintained anymore apparently. Migration is forced. Thanks a lot for your help.
